### ISSUE TITLE
If the launch url of the correctly end with a #, the registration parameter contains the # and authentication fails

### ISSUE THREAD

**Issue by fmeinhold** [xapijs/cmi5#208]
We are building a CMI5 course using vue and vue router. The router uses the # in the url to pass it's urls. The LMS adds the query parameters at the correct position, before the "#". Here's an example (edited for brevity and privacy):

https://cloud.scorm.com/sandbox/content/courses/xxxxxxxxxx/c1.test55d307ae-1d69-4fa0-998d-d80e98c0000e/0/content/index.html?actor=%7B%22objectType%22%3A%22Agent%22....kadvrrYw2G39M1JHsi9pTIxzpOoWazU9IjIVA2z6Eria0Zl2&registration=c40b873d-a4b1-4d51-bd05-de0f960d47e3#/

The registration parameter ends up incorrect, it contains the "#/". 

https://stackoverflow.com/questions/12682952/proper-url-forming-with-a-query-string-and-an-anchor-hashtag

I looked at 
` private getLaunchParametersFromLMS(): LaunchParameters {
    return XAPI.getSearchQueryParamsAsObject(
      window.location.href
    ) as LaunchParameters;
  }
`
and it uses window.location.href and then the method string split's by "?"- i would suggest to use window.location.search if possible. I have a pull request ready, if interested. 

And thanks for all the work!
-Felix

**Comment by CookieCookson** [comment]
Hi Felix! Thanks for raising this issue, it's an unfortunate oversight of me using the entire URL and not considering that there may be a hash involved for routing. (As a Vue developer I feel a bit ashamed not to have considered this already!)

I'd really appreciate a PR if you have one put together, would you feel comfortable adapting the tests to pass through a hash to test for this scenario too?

**Comment by fmeinhold** [comment]
Yes, I can send you a pull request including tests and  have everything
ready in my morning (CET).



Christian Cook ***@***.***> schrieb am Fr. 16. Dez. 2022 um
00:49:

**Comment by CookieCookson** [comment]
@fmeinhold this fix has now been released in 1.1.5 with a couple of dependency changes. Let me know if this new version has fixed your issue and we can close this one down 😃

**Comment by fmeinhold** [comment]
@CookieCookson thank you, issue is solved.
