### ISSUE TITLE
Expose data and modify Cmi5 constructor to allow implementation of Best Practice #17

### ISSUE THREAD

**Issue by nborko** [xapijs/cmi5#225]
Currently, information like the fetch token and other data needed to hydrate a Cmi5 instance is are private, which makes implementing cmi5 Best Practice # 17 difficult to achieve without significantly extending/overriding the Cmi5 class.

It would be nice if you could obtain a JSON-able object from the API (storable in e.g. SessionStorage) that includes all the necessary information to instantiate a Cmi5 object without having to go through initialize(), and then be able to supply that information to the constructor or a static factory function in order to recover a session from a browser refresh, as indicated in the Best Practice (provided below):

###  Best Practice # 17 – Persist AU Session State 

There are certain situations, such as browser window refresh, that may inadvertently cause cmi5 errors related to operations that must occur only once in a session.  To prevent such issues, AU’s should be designed to use non-volatile storage (local to AU) to preserve the state of following operations that have been performed during the session:

* Fetch URL token retrieval (which can only be called once in session)
* All cmi5 defined statements that can only be sent once in a session.

**Comment by CookieCookson** [comment]
@nborko thank you for using the CMI5 library and for raising the issue.

I will see what I can do to make the library work for various use cases in this session state scenario, its certainly something that is missing that would improve the developer (and user) experience.

Just thinking through ideas right now, maybe some form of `restore()` helper method may be useful here to abstract away any complicated re-initialisation.

**Comment by CookieCookson** [comment]
@nborko Thank you for your patience with this issue. I've made a couple of non-breaking changes which you can use to get/set the auth token in `@xapi/cmi5@1.2.0`:

- `getAuthToken()` returns the auth token for your initialized session. It's up to you to store this in the location of your choice e.g. sessionStorage.
- `initialize` now accepts an optional string parameter called `authToken`. If you provide this parameter this auth token gets used instead of attempting to get (POST) the auth token from the LMS via the fetch URL.

Please re-open the issue if this does not cover your use case.

**Comment by nborko** [comment]
I had 99% of the code required to support this API addition, so dropping in the new version worked. Thanks!

**Comment by nborko** [comment]
Well I spoke too soon. It seems that calling initialize() sends an "initialized" defined statement to the LRS, which can only be called once per session. Since this is a continuation of a previous session, I believe that sending the statement at the end of initialize() when authToken was passed in would be an error.

**Comment by CookieCookson** [comment]
@nborko `@xapi/cmi5@1.3.0` should now work as expected. A new helper method `getInitializedDate` has also been added, which will enable you to persist the original initialized date to be used in the `initialize` method when resuming a session. The first argument for `initialized` is now an object containing `authToken` and `initializedDate`.
