### ISSUE TITLE
how can we use in angular app to initialize  the Au  and how to use if we have ui-proxy layer on top of LRS .

### ISSUE THREAD

**Issue by amantarento** [xapijs/cmi5#258]

**Comment by amantarento** [comment]
@CookieCookson can  u please give me idea here.

**Comment by CookieCookson** [comment]
Hi @amantarento!

Have you had a chance to look at the [xAPI.js cmi5 documentation](https://www.xapijs.dev/cmi5-profile-library) and looked through the source code for the [cmi5 demo project](https://github.com/xapijs/cmi5-demo)? The demo is built using Stencil.js which is a different JS framework but has similar principles and demonstrates the library being used.

I'm not familiar with your LRS UI proxy, could you explain in more detail what your issue/concern is?

**Comment by amantarento** [comment]
@CookieCookson  yes i have gone through the documentation . About ui-proxy which is written in node js its nothing but one layer on top of communication between LMS server where my content is hosted .

**Comment by amantarento** [comment]
@CookieCookson  basically there should be one example how to use in angular framework .

**Comment by CookieCookson** [comment]
@amantarento If your UI proxy simulates a CMI5 conformant environment then this library will work with it out of the box. It follows all of the CMI5 principles for getting the query parameters from the URL and fetching the auth token using the `fetch` URL query parameter.

If you download the [CMI5 Demo](https://github.com/xapijs/cmi5-demo/releases/download/1.3.2/cmi5-demo.zip) archive and run it in your environment you will be able to see if it works successfully within your UI proxy.

As for the Angular example, I have very limited time to spend working on the xAPI.js suite so I won't be able to get something across to you soon. It is the case of following the [ES Module getting started instructions](https://www.xapijs.dev/cmi5-profile-library/getting-started#es-module-client-side-applications) to initialise the Au, and then using whatever additional methods you need to call for your particular use case e.g. `pass()`, `complete()`, `terminate()`.

If something isn't working as expected with the library, please put together a minimum use case in a repository or code sandbox and I will be able to investigate any issues you may have.

**Comment by amantarento** [comment]
@CookieCookson  i am doing like that  endpoint = 'https://cloud.scorm.com/lrs/8PXXTS0TNX/';

  constructor() {}

  ngOnInit() {
    //Actity provider creds, change with yours
    const username = 'EldKSSwyBtJgTf6_hjU';
    const password = 'LctzREIvq-JJRkAxF4g';

    //Encode to base64
    const auth = `Basic ${btoa(username + ':' + password)}`;

    //Create an instance of the wrapper
    let xApiWrapper = new XAPI(this.endpoint, auth);

    // we initilize our class member to this new object so we can use it in the onClick method as well
    this.xApiWrapper = xApiWrapper;
 but here instead of basic auth can't we pass authorization bearer token ?

**Comment by CookieCookson** [comment]
@amantarento It looks like you are using the xAPI wrapper, not the CMI5 wrapper. Is this correct?

Also, please be careful sharing your authentication credentials in a public conversation - if anyone else finds your comment they can send data to your SCORMCloud LRS, I suggest changing these if they are being used in a real project.
