### ISSUE TITLE
Use an instance of `XAPI` per instance of `Cmi5` in order to support more usage scenarios

### ISSUE THREAD

**Issue by emmanuel** [xapijs/cmi5#263]
Hi, and thanks for `xapi.js` and `cmi5.js`! We're using `xapi.js` in a backend (Node.js) context. We're interested in using the higher-level `Cmi5` class, but the strategy of relying on a single static XAPI client (via `Cmi5._xapi`) just doesn't work in that scenario (we'll have multiple XAPI clients with distinct auth, etc; one for each in-progress AU).

Would you be open to a PR refactoring the `Cmi5` class to initialize an instance of `XAPI` for each instance?

**Comment by CookieCookson** [comment]
Hi @emmanuel! I'm intrigued by your desired usage of using CMI5 in a backend context.

Looking at an old commit it was previously built so there was one xAPI instance per CMI5 instance but it was then switched to a singleton. I cannot find the exact reason why I decided to make the change to a singleton, but in #85 (Fixes #82) the intention was to only publicly expose the internal xAPI instance but as a by-product of the implementation method it meant it now shares the same xAPI instance.

I'll take a peek at your PR (Many thanks!) and see if the changes are suitable whilst retaining existing functionality.
