### ISSUE TITLE
propose static-singleton access for Cmi instance

### ISSUE THREAD

**Issue by beatthat** [xapijs/cmi5#51]
e.g. `Cmi5.get()` or `Cmi5.instance()`

Anywhere that we currently use cmi5 libs in assignable-unit apps, we really just want to access the global cmi5 singleton. Without static-singleton access, it puts extra burden on client code to figure out where to initialize the cmi5 instance and then how to make it accessible in different places in the code.

I can add this as a quick PR if you approve

**Comment by CookieCookson** [comment]
Good idea, I cannot see why we would need more than 1 instance in an AU, so a singleton would be beneficial.

I look forward to your PR!

**Comment by beatthat** [comment]
> Good idea, I cannot see why we would need more than 1 instance in an AU, so a singleton would be beneficial.
> 
> I look forward to your PR!

Great! Ready for review [here](https://github.com/xapijs/cmi5/pull/52)

**Comment by CookieCookson** [comment]
Thanks for the PR! Released in v0.4.0 🎉
