### ISSUE TITLE
How to implement this with captivate.

### ISSUE THREAD

**Issue by premkanish** [xapijs/cmi5#68]
let's say i publish content as xapi from adobe captivate and the zip file is uploaded to lms. How to implement this in the whole process.

**Comment by CookieCookson** [comment]
Hi @premkanish, thanks for opening an issue. 

Implementing this library would require the Captivate developers to integrate the cmi5 library into their publishing tools as a new export output alongside scorm, tincan etc. It's unfortunately not as simple as modifying the build output or adding in code snippets to your projects.

I hope this answers your issue - if you need Captivate to output to cmi5 I would put a formal feature request in with Adobe.

**Comment by premkanish** [comment]
Thanks for writing me back ! It would be great if Adobe captivate give us cmi5 output. Please proceed with the request.

Though cant i use this library https://github.com/cawerkenthin/cmi5-AU-Simulator and then use yours to fetch cmi5 statements.
