### ISSUE TITLE
easier way to pass extensions and test support

### ISSUE THREAD

**Issue by beatthat** [xapijs/cmi5#7]
First off, thanks for making this library!

I've been working on various projects that use xapi/cmi5 and we've built a couple versions of js libraries to support it, but I'd like to switch to your lib. 

The main blocker for us making that switch is that we have some apps that depend on passing result extensions with pass/fail/complete statements, and the signatures for those functions in this lib don't support passing extensions.

Would you be open to that feature in principal? If you are, we can make a fork, do the work and PR back to you.

I'm imagining the best and most general purpose way to handle this would be an optional callback function that transforms xapi statments before send, e.g.

```typescript
// a function that can apply an arbitrary transform
// to an xapi Statement, e.g. add extensions
interface StatementTransformFunction {
  transform: (s: Statement) => Statement;
}

// a catch-all for options that might be
// passed to cmi-send-statement functions
interface SendCmiStatementOptions {
  transform?: StatementTransformFunction;
}

class Cmi5 {
  public complete(s: Partial<Statement>, options: SendCmiStatementOptions = {}) : AxiosPromise<string[]> {
    ...
    this. sendCmi5DefinedStatement({...}, options)
  }

  public sendCmi5AllowedStatement(
    statement: Partial<Statement>,
    options: SendCmiStatementOptions = {}): AxiosPromise<string[]> {
    ...
    const mergedStatement: Statement = deepmerge.all([cmi5AllowedStatementRequirements, statement]) as Statement;
    const sendStatement = (options.transform)
      ? options.transform(mergedStatement)
      : mergedStatement;
    return this.connection.sendStatement(sendStatement);
  }
}
```

For motivation, the custom extension we most commonly use is one that supplies granular 'skill' scores to the result of an assignable unit. For example, in some interactive-training assignable units we have, the result might look like this:

```json
{
  "result": {
    "score": { "scaled": 0.8 },
    "extensions": {
      "https://ict.usc.edu/xapi/result/extension/skills": {
        "asks": 0.2,
        "evaluates": 0.9,
        "listens": 0.5,
      }
    }
  }
}
```

Curious if you know of a a more standards-based way to do the equivalent?

The last thing I want to add is that the cmi5 libraries we've developed inhouse have a suite of tests. Since they're testing cmi implementation over axios (via spies), should be not too hard to port our tests over to your library. Would you want those basic tests as a (separate) PR?

**Comment by CookieCookson** [comment]
Hey @beatthat - thanks for getting in touch, and its nice to know somebody is using the library other than myself! I'd love to see how the library could accommodate the needs of your projects, I haven't worked a great deal with extensions yet so bare with my understanding.

I like your idea of being able to transform requests, but I'm not sure if bundling an extra parameter with each method would be the cleanest approach (at least for now with the lack of other config required per request). From using libraries like Axios, you have the ability to set a default `transformRequest` for all calls when initialising the library instance.

This could be an optional options parameter passed in the constructor, containing a transformRequest/transformStatement option. This option can then be picked up within the `sendCmi5AllowedStatement` method (exactly like you have demonstrated above).

One downside I can think of going for this approach would be having to identify what type of statement/request is being made and only modifying the intended statements.

Let me know what you think!

PS - tests sound good. I have some very basic tests implemented on the @xapijs/xapi and @xapijs/scorm libraries using Jest, but haven't brought anything into this library yet.

**Comment by beatthat** [comment]
Thanks for getting back so quickly. I don't know if the global option would work for our case because we really just want to pass specific extensions on specific statements. 

I definitely understand the concern about cluttering the API. Just to make sure clear though, if we went with the `options` route, that would be an optional parameter so the api would be backwards compatible. The reason I suggested making that new (optional) param an options object instead of just the `transform` function as a standalone was to leave space for any other options you might want to add in the future without breaking backwards compatibility in user call signatures

RE tests: let me take a look next couple days at forking this repo and just see how hard it would be to apply the tests we already have

**Comment by CookieCookson** [comment]
After sleeping on the idea, I think your approach is the most suitable 👍 I'm happy for you to proceed with a PR of these improvements!

For some of the methods e.g. interaction helpers, they have quite a lengthy list of parameters already. I'm considering combining these into a single object instead whilst the library is still in pre-release stages in case any additional parameters for statements need to be added in the future.

**Comment by beatthat** [comment]
Great! I'll have some time to fork and start that PR this afternoon. Will send you a draft when ready.

**Comment by CookieCookson** [comment]
Nice one. If you want to take a look at how I've tested the other xapijs libraries, each has a .spec.ts file:
https://github.com/xapijs/xapi/blob/master/src/XAPI.spec.ts
https://github.com/xapijs/scorm/blob/master/src/SCORM.spec.ts

In terms of CI, GitHub Actions is preferred and the other libs use that too! You can see my crude attempt here:
https://github.com/xapijs/xapi/blob/master/.github/workflows/nodejs.yml

**Comment by beatthat** [comment]
Great. Have an initial draft PR [here](https://github.com/xapijs/cmi5/pull/16). I think repo setting maybe don't allow me to request review?

I don't have github actions in yet, but was going to add that next.

Let me know what you think
