### ISSUE TITLE
How to search LRS with CMI5 package?

### ISSUE THREAD

**Issue by OuttaLineNomad** [xapijs/cmi5#82]
Is there a way to search in the LRS with this package? I use every other part of this library, I just need the ability to load my learners previous activities to the package. Do you have any solutions?

**Comment by CookieCookson** [comment]
Hi @OuttaLineNomad, thanks for raising the issue. You've raised a very good question, and I think there can be some work done to make this happen. Under the hood it has the full xAPI.js xAPI Wrapper library running, but it is not exposed.

Am I right in thinking you want to use standard xAPI calls using the cmi5 authentication credentials? (e.g. get statements, state etc) If so, as a hacky workaround for the short term, you can do:

![image](https://user-images.githubusercontent.com/3473396/113110807-67da9b80-91ff-11eb-8e57-620a3c01e8fe.png)

Which will expose the internal instance of the xAPI Wrapper library (You will have to install the xAPI Wrapper library for the type safety).

For a more long term solution, do you think we should expose this publicly? e.g. `this.cmi5.getXAPIWrapper()` could be made available as a helper method.

**Comment by OuttaLineNomad** [comment]
Thank you for the fast response. I think exposing the xAPI wrapper as a helper method would be great.

**Comment by CookieCookson** [comment]
Released in 1.1.0, sorry for the wait @OuttaLineNomad.
